# Generated by Django 4.1.3 on 2022-12-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_customer_address_customer_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total_amount_field',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
