# Generated by Django 4.1.3 on 2022-12-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transaction_total_amount_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='total_amount_field',
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_amount',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
