# Generated by Django 4.1.3 on 2022-12-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_filter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='timestamp_gt',
            new_name='timestamp_greater_than',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='timestamp_lt',
            new_name='timestamp_lower_than',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='total_amount_gt',
            new_name='total_amount_greater_than',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='total_amount_lt',
            new_name='total_amount_lower_than',
        ),
    ]
