# Generated by Django 4.1.3 on 2022-12-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_timestamp_gt_filter_timestamp_greater_than_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='filter',
            name='timestamp_greater_than',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='timestamp_lower_than',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='total_amount_greater_than',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='total_amount_lower_than',
            field=models.IntegerField(blank=True),
        ),
    ]
