# Generated by Django 4.1.3 on 2022-12-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_transaction_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='total_amount',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
