# Generated by Django 4.1.3 on 2022-12-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_transaction_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='timestamp_greater_than',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='timestamp_lower_than',
        ),
    ]
